### ISSUE TITLE
TypeError: cannot read property 'nodetype' of undefined

### ISSUE THREAD

**Issue by gvbrakel** [chieffancypants/angular-hotkeys#227]
I use karma for writing unit tests. When executing these, at random places the following error occurs:

Chrome 50.0.2661 (Windows 7 0.0.0) [Testsuite A] [model: <random> suite] should be able to determine the inverse point of a group transform FAILED
    TypeError: Cannot read property 'nodeType' of undefined
        at ja (c:/test/angular.min.js:55:360)
        at X (c:/test/angular.min.js:54:343)
        at X (c:/test//angular.min.js:55:6)
        at X (c:/test/angular.min.js:55:6)
        at J (c:/test/angular.min.js:52:378)
        at $get (c:/test/angular-hotkeys/build/hotkeys.min.js:7:4455)
        at Object.e [as invoke](c:/test/angular.min.js:40:19)
        at c:/test/angular/angular.min.js:41:343
        at d (c:/test/angular.min.js:39:220)
        at Object.e [as invoke](c:/test/angular.min.js:39:490)

This happens outside the actual tests, inside the call  'jasmineEnv.execute()'.

Any idea?

**Comment by gustiando** [comment]
@gvbrakel did you ever figure out what the issue was? I'm having the same error sporadically, super annoying.
